<?php
namespace Apps\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class Users extends ActiveRecord
{
    //your database connection name
    protected $database = 'cygnite';

    // your table name here
    //protected $tableName = 'user';

    protected $primaryKey = 'id';

   // public $perPage = 5;

    public function __construct()
    {
        parent::__construct();
    }

    public function skip()
    {
        return array('created_at', 'updated_at');
    }
}// End of the User Model