<!--<ng-include src="'assets/templates/navbar.php'"></ng-include>-->

<div class="row">
    <div class="col-sm-12 pull-right">

        <ul class="nav navbar-nav pull-right">
            <!-- Right side menu -->
            <li > <a href="#">
                    Welcome, {{ username }}
                </a>
            </li>
            <li> <a href="index.php/angular/#/logout">Logout</a> </li>
        </ul>
    </div>
</div>

<h3> {{ title }} </h3>

<div class="row">
    <div class="col-sm-12">
        <div class="col-sm-8 pull-left" ng-show="content">
            <p> Explore Awesome <a href='http://www.cygniteframework.com/2013/08/routing.html'>{{ cygnite }} </a> + <a href='http://angularjs.org/'>{{ angular }} </a> </p>
			
			<p>Tutorial Part1: Building A Simple Product Management App Using Angular JS + Cygnite PHP + Bootstrap </p>
			
			<p>You may use Cygnite PHP Framework and Angular JS to build your next awesome web application. </p>
			
			<p> Keep Visiting for Tutorial Part 2 where we will extend the app and build CRUD.</p>

        </div>

    </div>

</div>




