<?php 

use Cygnite\Database\Migration;
use Cygnite\Database\Schema;

/**
* This file is generated by Cygnite Migration Command
* You may use up and down method to create migration
*/

class Inventory extends Migration
{

    protected $database = 'cygnite';
	/**
	 * Run the migrations up.
	 *
	 * @return void
	 */
	public function up()
	{
		//Your schema to migrate
        Schema::instance(
            $this,
            function ($table) {

                $table->tableName = 'inventory';

                $table->create(
                    array(
                        array('name'=> 'id', 'type' => 'int', 'length' => 11,
                            'increment' => true, 'key' => 'primary'),
                        array('name'=> 'item_name', 'type' => 'string', 'length' =>100),
                        array('name'=> 'shop', 'type' => 'string', 'length'  =>16),
                        array('name'=> 'quantity', 'type' => 'string', 'length'  =>20),
                        array('name'=> 'price', 'type' => 'decimal', 'length'  =>'10,2'),
                        array('name'=> 'created_at', 'type' => 'datetime', 'length'  =>"DEFAULT '0000-00-00 00:00:00'"),
                        array('name'=> 'updated_at', 'type' => 'datetime', 'length'  =>"DEFAULT '0000-00-00 00:00:00'"),
                    ),
                    'InnoDB',
                    'latin1'
                )->run();
            }
        );
    }

	/**
	 * Revert back your migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		 //Roll back your changes done by up method.

        Schema::instance(
            $this,
            function ($table) {
                $table->tableName = 'inventory';
                $table->drop()->run();
            }
        );
		 
	}
}// End of the Migration
