<?php 

use Cygnite\Database\Migration;
use Cygnite\Database\Schema;

/**
* This file is generated by Cygnite Migration Command
* You may use up and down method to create migration
*/

class Users extends Migration
{

    /* Your database name */
    protected $database = 'cygnite';

	/**
	 * Run the migrations up.
	 *
	 * @return void
	 */
	public function up()
	{
		//Your schema to migrate
        Schema::instance(
            $this,
            function ($table) {

                $table->tableName = 'users';

                $table->create(
                    array(
                        array('name'=> 'id', 'type' => 'int', 'length' => 11,
                            'increment' => true, 'key' => 'primary'),
                        array('name'=> 'name', 'type' => 'string', 'length' =>100),
                        array('name'=> 'email', 'type' => 'string', 'length'  =>150),
                        array('name'=> 'password', 'type' => 'string', 'length'  =>150),
                        array('name'=> 'country', 'type' => 'string', 'length'  =>50),
                        array('name'=> 'age', 'type' => 'int', 'length'  =>11),
                        array('name'=> 'created_at', 'type' => 'datetime', 'length'  =>"DEFAULT '0000-00-00 00:00:00'"),
                        array('name'=> 'updated_at', 'type' => 'datetime', 'length'  =>"DEFAULT '0000-00-00 00:00:00'"),
                    ),
                    'InnoDB',
                    'latin1'
                )->run();
            }
        );

        $crypt = new \Cygnite\Common\Encrypt();

        $data = array(
            'name' => 'Admin',
            'email' => 'admin@cygnite.com',
            'password' => $crypt->encode('admin@123'),
            'country' => 'United States',
            'age' => '26',
            'created_at' => date( 'Y-m-d H:i:s'),
            'updated_at' => date( 'Y-m-d H:i:s')
        );

        $this->insert('users', $data);
		
	}

	/**
	 * Revert back your migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		 //Roll back your changes done by up method.
        $this->trash(array(1));

        Schema::instance(
            $this,
            function ($table) {
                $table->tableName = 'users';
                $table->drop()->run();
            }
        );
		 
	}
}// End of the Migration
